all:
  vars:
    ansible_python_interpreter: '/usr/bin/python3'
  children:
    mysql_master:
      hosts:
        vm2:    

    mysql_slave1:
      hosts:
        vm1:

    mysql_slave2:
      hosts:
        vm3:

    mysql_cluster:
      hosts:
        vm1:
        vm2:    
        vm3:
    
    stage:
      hosts:
        vm1:
          ansible_host: 192.168.122.11
        vm2:
          ansible_host: 192.168.122.12
        vm3:
          ansible_host: 192.168.122.13
          